# Generated by Django 2.1 on 2020-02-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gist_kakao_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mall',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mall',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Mall',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
