# Generated by Django 2.1 on 2020-02-16 02:11

from django.db import migrations, models
import gist_kakao_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gist_kakao_api', '0002_auto_20200208_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeteriaMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('menu_img', models.ImageField(upload_to=gist_kakao_api.models.date_upload_to)),
            ],
        ),
    ]
