# Generated by Django 2.1 on 2020-02-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gist_kakao_api', '0003_cafeteriamenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeteriamenu',
            name='cafeteria',
            field=models.IntegerField(default=1),
        ),
    ]
