# Generated by Django 2.1 on 2020-02-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gist_kakao_api', '0005_cafeteriamenu_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeteriamenu',
            name='menu_img',
            field=models.URLField(),
        ),
    ]
