# Generated by Django 2.1 on 2020-02-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gist_kakao_api', '0006_auto_20200216_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
    ]
